from enum import IntEnum


class LoginStatus(IntEnum):
    CONNECTED = 1
    DISCONNECT = 2
    LOGIN_SUCCESS = 3
    LOGIN_FAILED = 4
    UNAUTHORIZED = 5
    AUTH_FAILED = 6
    AUTH_EXPIRED = 7
    AUTH_SUCCESS = 8


class ProtocolConnectionStatus(IntEnum):
    DISCONNECT = 0
    CONNECTED = 1
    LOGIN_SUCCEED = 2


class PacketCommand(IntEnum):
    PACKET_CMD_LOGIN = 0x01
    PACKET_CMD_QRCODE_RECORD_CTL = 0x02
    PACKET_CMD_HEARTBEAT = 0x04
    PACKET_CMD_LOGOUT = 0x05
    PACKET_CMD_DTU_UPDATE = 0x07
    PACKET_CMD_DTU_PARAM_GET = 0x08
    PACKET_CMD_DTU_PARAM_SET = 0x09
    PACKET_CMD_PGM_UPDATE_NOTIC = 0x0A
    PACKET_CMD_RELOCATION = 0x0B
    PACKET_CMD_NONNET_WALKMODE = 0x0D
    PACKET_CMD_CAMERA_SHARE_SWITCH = 0x10
    PACKET_CMD_CAMERA_SHARE_SWITCH_CHECK = 0x11
    PACKET_CMD_COMMUNICATION_CHECK_STATUS = 0x12
    PACKET_CMD_FUNC_AREA_SETTINGS = 0x14
    PACKET_CMD_FUNC_AREA_QUERY = 0x15
    PACKET_CMD_MAP_ACQUISITION_CTL = 0x16
    PACKET_CMD_FLOOR_REGISTER = 0x21
    PACKET_CMD_FLOOR_DOOR_CTRL = 0x22
    PACKET_CMD_BUILDING_INFO = 0x23
    PACKET_CMD_BUILDING_ELEVATOR = 0x24
    PACKET_CMD_BUILDING_MAP = 0x25
    PACKET_CMD_LIFT_INFO_QUERY = 0x27
    PACKET_CMD_DISPATCH_MODE_SWITCH = 0x30
    PACKET_CMD_DISPATCH_ORDER_DOWN = 0x31
    PACKET_CMD_REMOTE_CONTROL = 0x37
    PACKET_CMD_ROTATION_CONTROL = 0x38
    PACKET_CMD_VIDEO_SWITCH = 0x41
    PACKET_CMD_VIDEO_SWITCH_SEARCH = 0x42
    PACKET_CMD_SPECIAL_POINT_SETTING = 0x45
    PACKET_CMD_SCREEN_OPERATION = 0x46
    PACKET_CMD_GOTO_AVOIDANCE_POINT = 0x47
    PACKET_CMD_HOIST_UP_RESULT = 0x48
    PACKET_CMD_HOIST_CTRL = 0x49
    PACKET_CMD_HOIST_QUERY = 0x4A
    PACKET_CMD_HOIST_SET = 0x4B
    PACKET_CMD_FICM_ERROR_UPLOAD = 0x50
    PACKET_CMD_FICM_VERSION = 0x51
    PACKET_CMD_DRIVING_RECORD_SWITCH = 0x52
    PACKET_CMD_DRIVING_FILE_MANAGE = 0x53
    PACKET_CMD_DRIVING_FILE_FIND = 0x54
    PACKET_CMD_POWER_MANAGE = 0x55
    PACKET_CMD_TIME_TASK_SYNC = 0x56
    PACKET_CMD_INFRARED_SWITCH = 0x57
    PACKET_CMD_TBOX_VERSION = 0x58
    PACKET_CMD_TBOX_VIN_ICCID = 0x59
    PACKET_CMD_POSITION = 0x5A
    PACKET_CMD_TASK_CTRL = 0x5B
    PACKET_CMD_BACK_PILE = 0x5C
    PACKET_CMD_TIMER_ON_OFF = 0x5D
    PACKET_CMD_ELEVATOR_NUMBHER = 0x5E
    PACKET_CMD_ELEVATOR_POINT = 0x5F
    PACKET_CMD_TASK_DISTRIBUTION = 0x60
    PACKET_CMD_GO_START = 0x61
    PACKET_CMD_RESTORE_FACTORY = 0x62
    PACKET_CMD_TRACK_TO_POINT = 0x63
    PACKET_CMD_TRACKING_TASK = 0x64
    PACKET_CMD_CABINET_DOOR_STATE = 0x65
    PACKET_CMD_CLEAR_ERROR_CODE = 0x66
    PACKET_CMD_WIFI_CTL = 0x67
    PACKET_CMD_LIGHT_CTL = 0x68
    PACKET_CMD_VIDEO_UPLOAD_CTL = 0x6A
    PACKET_CMD_EMBODIED_INTELLIGENCE_STATU = 0x6C
    PACKET_CMD_PARAM_SET = 0x77
    PACKET_CMD_PARAM_GET = 0x78
    PACKET_CMD_REFLASH_FILE = 0x7A
    PACKET_CMD_FILE_DOWNLOAD = 0x7D
    PACKET_CMD_BRAKE_CONTROL = 0x83
    PACKET_CMD_AREA_SWEEPING_MODE_SETTING = 0xA6
    PACKET_CMD_TASK_SWEEPING = 0xA7
    PACKET_CMD_TOUCH_UP_RECORD = 0xA8
    PACKET_CMD_AREA_SWEEPING_MODE_SEARCH = 0xA9
    PACKET_CMD_MAPPING_TABLE = 0xC0
    PACKET_CMD_AVOIDANCE_POINT_SETTING = 0xC5
    PACKET_CMD_AVOIDANCE_POINT_SEARCH = 0xC6
    PACKET_CMD_NOTICE_START = 0xCF
    PACKET_CMD_POINT_ARRIVED = 0xD0
    PACKET_CMD_FUNC_AREA_ARRIVED_STATUS = 0xD1
    PACKET_CMD_SWEEPING_CTL = 0xD3
    PACKET_CMD_DISPATCH_CTL_INSTRUCTION = 0xDA
    PACKET_CMD_TBOX_ERROR_DISPLAY = 0xE0
    PACKET_CMD_QRCODE_LIST_UPLOAD = 0xE1
    PACKET_CMD_CHARGING = 0xE3
    PACKET_CMD_CHARGING_STATE = 0xE4
    PACKET_CMD_TASK_STATE = 0xE5
    PACKET_CMD_FLOOR_STATE = 0xE6
    PACKET_CMD_REMOTE_REFRESH_STATE = 0xE7
    PACKET_CMD_UNDERPAN_STATE = 0xE8
    PACKET_CMD_CHASSIS_STATIC_INFO = 0xE9
    PACKET_CMD_CHASSIS_ABNORMAL_REPORT = 0xEA
    PACKET_CMD_FUNCTIONAL_AREA_WAIT_REPORT = 0xEB
    PACKET_CMD_EMBODIED_INTELLIGENCE_TASK = 0xED
    PACKET_CMD_POSE_INFO = 0xEE
    PACKET_CMD_DTU_PARAM_REPORT = 0xF0
    PACKET_CMD_PROTOCOL_END = 0xFF


class RelocationType(IntEnum):
    POSE = 0x01
    LAST_SHUTDOWN = 0x02
    FULL_MAP = 0x03
    WALL_CODE = 0x04
    PILE_CODE = 0x05
    CEILING = 0x06
    REFLECTIVE_STRIP = 0x07
    AUX_DISABLE = 0x0F


class MapAcquisitionCommand(IntEnum):
    INCREMENTAL = 0x01
    FINISH = 0x02
    CLEAR = 0x03


class CommunicationControlCommand(IntEnum):
    HOST_CLOSE = 0
    HOST_OPEN = 1
    WIFI_CLOSE = 2
    WIFI_OPEN = 3
    FOUR_G_CLOSE = 4
    FOUR_G_OPEN = 5
    EXTERNAL_NET_CLOSE = 6
    EXTERNAL_NET_OPEN = 7
    HOST_MODIFY = 8
    WIFI_CONNECT = 9


class TaskType(IntEnum):
    AUTO_DRIVING = 0x00
    AUTO_CHARGING = 0x01
    LOCAL_CHARGING = 0x02
    CLOUD_CHARGING = 0x03
    PARALLEL_DRIVING = 0x04
    REFRESH = 0x05
    TIMER_SHUTDOWN = 0x06
    REMOTE_SLEEP = 0x08
    PILE_RETRY = 0x09
    CLEANING = 0x0A
    DISPATCH = 0x14
    HOIST_UP = 0x30
    HOIST_DOWN = 0x31


class TaskControl(IntEnum):
    CANCEL = 0
    PAUSE = 1
    RESUME = 2


class BrakeControl(IntEnum):
    PULL = 0
    RELEASE = 1


class RotationType(IntEnum):
    ABSOLUTE = 0
    RELATIVE = 1


class HoistControlMode(IntEnum):
    RATIO = 0
    HEIGHT = 1


class HoistSetCommand(IntEnum):
    CLEAR_FAULT = 0
    SET_ZERO = 1


__all__ = [
    "BrakeControl",
    "CommunicationControlCommand",
    "HoistControlMode",
    "HoistSetCommand",
    "LoginStatus",
    "MapAcquisitionCommand",
    "PacketCommand",
    "ProtocolConnectionStatus",
    "RelocationType",
    "RotationType",
    "TaskControl",
    "TaskType",
]
